blogg_modell/blogg_modell/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blogg/', include('main.urls')),
    path('register/', views.register, name="register"),
    path('', include("django.contrib.auth.urls")),
]

blogg_modell/main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name="search"),
    path('weather/', views.weatherAPI, name="weatherAPI"),
    path('add/', views.weatherSearch, name="weatherSearch"),
    path('api/', views.myAPI, name="myAPI"),
]

blogg_modell/main/models.py
import datetime
from django.db import models
from django.utils import timezone

#Models go here

class Author(models.Model):
    name        = models.CharField      (max_length = 50)
    joined      = models.DateTimeField  ( 'date joined' )
    job_title   = models.CharField      (max_length = 50)
    def __str__(self):
        return self.name

class Post(models.Model):
    title       = models.CharField      (max_length = 100)
    content     = models.TextField      (max_length = 5000)
    pub_date    = models.DateTimeField  ('date published')
    tags        = models.CharField      (max_length = 300)
    author      = models.ForeignKey     (Author, on_delete = models.CASCADE)
    def __str__(self):
        return self.title

blogg_modell/main/forms.py
from django import forms
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

stringLabel="Input number of days to forecast (Numbers from 1 to 10)"
class NewTaskForm (forms.Form):
    city = forms.CharField(label="")
    days = forms.IntegerField(min_value=1, max_value=3, label="")
    #max value upp till 10 men den verkar inte funka längre på webbsidan så ta max 3 för nu

blogg_modell/main/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponse, HttpResponseRedirect
from .models import Author, Post
from django.template import loader
from django.urls import reverse
from django.views import generic
from django import forms
from django.forms.forms import Form
import requests
from .forms import RegisterForm, NewTaskForm
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

#views go here

#Home/Index
def index(request):
    post = Post.objects.all()
    return render(request, "blogg/index.html", {'queryset':post})

#Register account
def register(response):
    if response.method == "POST":
        form = RegisterForm(response.POST)
        if form.is_valid():
            form.save()
        
        return redirect("/blogg")
    else: 
        form = RegisterForm()

    return render(response, 'registration/register.html', {"form":form})


#Search bar
def search(request):
    if request.method=="POST":
        author = request.POST['search']
        print(author)
        try:
            searched_author = Author.objects.get(name=author)
            posts_by_author = Post.objects.filter(author=searched_author)
        except:
            searchResponse = "Your request didn't match anything in our database"
            return render(request, "blogg/search.html", {'response':searchResponse,})
        else:
            return render(request, "blogg/search.html", {'queryset':posts_by_author})
    else:
        return render(request, "blogg/search.html")


#Pokemon API
def myAPI(request):
    response = requests.get('https://pokeapi.co/api/v2/pokemon/charizard')
    context = response.json()
    types = [context['types'][0]['type']['name']]
    if context['types'][1]['type']['name']:
        types.append(context['types'][1]['type']['name'])
    return render(request, 'blogg/myapi.html', {
        'pokemon_name': context['name'],
        'pokemon_type': types})




#Weather API

apiList={}

def weatherSearch(request):
    key = "4f14ec29516d493785470208222904"
    tasklist=[]
    if request.method=="POST":
        form=NewTaskForm(request.POST)
        if form.is_valid():
            city=form.cleaned_data["city"]
            days=form.cleaned_data["days"]
            tasklist.append(city)
            tasklist.append(days)
            response = requests.get('http://api.weatherapi.com/v1/forecast.json?key='+key+'&q='+city+'&days='+str(days)+'&aqi=no&alerts=no')
            context = response.json()
            if context:
                for stuff in context["current"]:
                    if stuff == "condition":
                        for condiment in context["current"]["condition"]:
                            tasklist.append(condiment)
                    else:
                        tasklist.append(stuff)
                for stuff2 in context["current"]:
                    tasklist.append(stuff2)

                #dictionary to be used in weather.html with template python
                apiList = {
                'icon': [context['current']['condition']['icon']],
                'name': context["location"]["name"],
                'temp_c': [context["current"]["temp_c"]],
                'text': [context['current']['condition']['text']],
                'date': [context['current']['last_updated']],
                }
                #iterate and add object to dictionary value lists
                for i in range(1, days):
                    apiList['icon'].append(context['forecast']['forecastday'][i]['day']['condition']['icon'])
                    apiList['temp_c'].append(context['forecast']['forecastday'][i]['day']['avgtemp_c'])
                    apiList['text'].append(context['forecast']['forecastday'][i]['day']['condition']['text'])
                    apiList['date'].append(context['forecast']['forecastday'][i]['date'])
                
            return render(request, 'blogg/weather.html', {
                'tasklist':tasklist,
                'form':form,
                "mydict":apiList,
                'range': range(days),
                'request': city,
            })
        else:
            return redirect('http://127.0.0.1:8000/blogg/')
    return render(request, 'blogg/weather.html', {
        "form":NewTaskForm()
    })


def weatherAPI(request):
    key = "4f14ec29516d493785470208222904"
    city = "Stockholm"
    days = 1
    response = requests.get('http://api.weatherapi.com/v1/forecast.json?key='+key+'&q='+city+'&days='+str(days)+'&aqi=no&alerts=no')
    context = response.json()
    if context:
        return render(request, 'blogg/weather.html', {
        "form":NewTaskForm(),
        'day': days,
        })

    else:
        return redirect('http://127.0.0.1:8000/blogg/')

blogg_modell/main/templates/blogg/index.html
{% extends "navbar/nav.html" %}
{% load static %}
{% block extrahead %}
<link rel="stylesheet" href="{% static 'blogg/style.css' %}">
{% endblock %}
{% block content %}
{% for post in queryset %}
    <div class="mainpage">
        <h2>{{post.title}}</h2><br>
        <p id="author">Written by: {{post.author}}</p>
        <p class="content">{{post.content}}</p>
    </div>
{% endfor %}
{% endblock %}

blogg_modell/main/templates/blogg/myapi.html
<h3> Mitt api </h3>
{% if pokemon_name %}
<p> Min pokemon är: {{pokemon_name}} och har typerna <br>
    {% for type in pokemon_type %}
    {{type}} <br>
    {% endfor%}
{% endif %}

blogg_modell/main/templates/blogg/search.html
{% extends "navbar/nav.html" %}
{% load static %}
{% block extrahead %}
<link rel="stylesheet" href="{% static 'blogg/style.css' %}">
{% endblock %}

{% block content %}
{% if queryset %}
{% for post in queryset %}

<div class="mainpage">
    <h2>{{post.title}}</h2><br>
    <p id="author">Written by: {{post.author}}</p>
    <p class="content">{{post.content}}</p>
</div>
{% endfor %}
{% endif %}

{% if response %}
<p>{{response}}</p>
{% endif %}

{% endblock %}

blogg_modell/main/templates/blogg/weather.html
{% extends "navbar/nav.html" %}
{% load static %}
{% load index %}
{% block extrahead %}
<link rel="stylesheet" href="{% static 'blogg/style.css' %}">
{% endblock %}
{% block content %}
    <form class="forecastAPI" action="{% url 'main:weatherSearch' %}" method="POST">
        {% csrf_token %}
        <label for="city">Name a city and how many days of forecast you want.</label><br>
        {{form}}

        <input type="submit" value="add">
    </form>

<!-- <form action="{% url 'main:weatherSearch' %}" method="POST">
    {% csrf_token %}
    <label for="quantity">How many days of forecast would you like?</label>
    <input type="number" step="1" id="quantity" name="quantity" min="1" max="10" value="1">
    <input type="submit" value="search">
</form> -->

{% for i in range %}
<div class="mainpage">
    {% if forloop.counter == 1 %}
        <p>Today</p>
    {% else %}
        <p>Day: {{forloop.counter}}</p>
    {% endif %}
    {% for key, value in mydict.items %}
        {% if key == "name" %}
            <p>City: {{value}}</p>
        {% elif key == "temp_c" %}
            <span>Temperature: {{value|index:i}} °C</span>
        {% elif key == "text" %}
            <span id="text">Weather: {{value|index:i}}</span>
        {% elif key == "date" %}
            <p>Forecast date {{value|index:i}}</p>
        {% elif key == "icon" %}
            <img src="{{value|index:i}}">
        {% else %}
            <p>{{key}}: {{value}}</p>
        {% endif %}
    {% endfor %}
</div>

{% endfor %}
{% endblock %}

blogg_modell/main/templates/navbar/nav.html
{% load static %}
<html>
    <head>
        <link rel="stylesheet" href="{% static 'navbar/style.css' %}">
        {% block extrahead %}{% endblock %}
    </head>
<body>
    <div class="topnav">
        <a class="active" href="/blogg/">Home</a>
        <a href="/blogg/weather/">Weather Forecast</a>
        {% if user.is_authenticated %}
            <p id="navUser">You are logged in as {{user}}.</p>
        {% else %}
            <a href="/login">Login</a>
        {% endif %}
        <form action="{% url 'main:search' %}" method="post">
            {% csrf_token %}
            <input type="text" placeholder="Search.." name="search">
        </form>
    </div>
    {% block content %}
        <p>
            (Block Content goes here.)
        </p>
    {% endblock %}
</body>
</html>